 const Data = [
    {
        id: 1,
        name: "Fall Limited Edition Sneakers",
        originalPrice:250,
        discountPrice: 125.00,
        image_1: "https://fm-ecommerce-product-page-cyan.vercel.app/_next/static/media/image-product-1.c95272fd.jpg",
        image_2: "https://fm-ecommerce-product-page-cyan.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-product-2.3c0d837c.jpg&w=640&q=75",
        image_3: "https://fm-ecommerce-product-page-cyan.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-product-3.18849313.jpg&w=640&q=75",
        image_4: "https://fm-ecommerce-product-page-cyan.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage-product-4.ed713294.jpg&w=640&q=75",
        description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they’ll withstand everything the weather can offer.",
        rating: 4.2,
        discount: 50,
        category: "men"
      },
      {
        id: 2,
        name: "Men Casual shoes",
        originalPrice:250,
        discountPrice: 125.00,
        image_1: "https://m.media-amazon.com/images/I/51yd2zN+zXL._AC_UF1000,1000_QL80_.jpg",
        image_2: "https://5.imimg.com/data5/ANDROID/Default/2022/2/MJ/AO/ZH/73718625/product-jpeg.jpg",
        image_3: "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/g/06/cded5646-331f-4969-a6ad-32c917692394.jpg",
        image_4: "https://m.media-amazon.com/images/I/51CVSmzldnL._AC_UY1000_.jpg",
        description: "Perfect for long runs with amazing cushioning.",
        rating: 4.4,
        discount: 50,
        category: "men"
      },
      {
        id: 3,
        name: "ASIAN Men's Wonder Sports Running Casual Sneaker",
        originalPrice:1299,
        discountPrice: 844,
        image_1: "https://m.media-amazon.com/images/I/41mWz2aRrTL._SY695_.jpg",
        image_2: "https://m.media-amazon.com/images/I/41iZ9P7LtSL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/51tQT7QqJnL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/716cBIZmfFL._SY500_.jpg",
        description: "ASIAN Men's Wonder Sports Running,Walking & Gym Shoes with Casual Sneaker Lightweight Lace-Up Shoes for Men's Delta-20",
        rating: 3.9,
        discount: 35,
        category: "men"
      }, 
      {
        id: 4,
        name: "Puma Unisex MAPF1 Neo Cat 2.0 Sneaker",
        originalPrice:6999,
        discountPrice: 2239,
        image_1: "https://m.media-amazon.com/images/I/41T+S09+2lL._SY695_.jpg",
        image_2: "https://m.media-amazon.com/images/I/41mtvgoR6WL._SY695_.jpg",
        image_3: "https://m.media-amazon.com/images/I/51wm7skz1aL._SY695_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61MWFDInJzL._SY695_.jpg",
        description: "Product Story: Accelerate your style to F1® speeds. These sleek yet sturdy low-profiles propel you forward in effortless style. A perforated synthetic upper and webbing details give an unmistakable motorsport edge. FEATURES & BENEFITS The upper of the shoes is made with at least 20% recycled materials DETAILS Regular fit Synthetic upper Lace closure Rubber outsole Perforation details on the quarter and vamp Webbing in spectra green on the tongue PUMA and Mercedes-AMG Petronas F1® branding details",
        rating: 4.1,
        discount: 68,
        category: "men"
      },
      {
        id: 5,
        name: "U.S. POLO ASSN. Men's Sneaker",
        originalPrice:3599,
        discountPrice: 2161,
        image_1: "https://m.media-amazon.com/images/I/512rTHmiN-L._SY695_.jpg",
        image_2: "https://m.media-amazon.com/images/I/51Mz2XQXjsL._SY695_.jpg",
        image_3: "https://m.media-amazon.com/images/I/51RytC43xtL._SY695_.jpg",
        image_4: "https://m.media-amazon.com/images/I/51jFsDB4noL._SX695_.jpg",
        description: " Arvind Lifestyle Brands Limited  Arvind Lifestyle Brands Limited, Arvind Lifestyle Brands Limited  Arvind Lifestyle Brands Limited",
        rating: 4.0,
        discount: 40,
        category: "men"
      },
      {
        id: 6,
        name: "SPARX Mens Sm 732 Sneaker",
        originalPrice:1099,
        discountPrice: 878,
        image_1: "https://m.media-amazon.com/images/I/51TLCF2hwBL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61dTYadgpWL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/61flxI5UvUL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61N6u-mhCSL._SY500_.jpg",
        description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they’ll withstand everything the weather can offer.",
        rating: 4.1,
        discount: 20,
        category: "men"
      },
      {
        id: 7,
        name: "U.S. POLO ASSN. Men's Sneaker",
        originalPrice:2999,
        discountPrice: 1859,
        image_1: "https://m.media-amazon.com/images/I/71aFuiEntML._SY500_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61SuI96zREL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/617afbGpYoL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61wYurrpAOL._SY500_.jpg",
        description: "U.S. Polo Assn.'s colour-block stylish fashion sneakers have gained a refined status thanks to their minimalist design and superior construction. Designed with comfort and regular wear in mind, they make great all-rounders. They are framed with structured insoles for 24*7 cushioning and flexible outsole which flexes with your feet, they're easy to live and commute with. Their superior grip and cushioned interiors provide all day comfort, so you can team them with your athleisure in style.",
        rating: 4.1,
        discount: 38,
        category: "men"
      },
      {
        id: 8,
        name: "JQR Men's Sneaker,Trendy,Casual,Stylish Urban & Lifestyle Shoes",
        originalPrice:2899,
        discountPrice: 899,
        image_1: "https://m.media-amazon.com/images/I/618b2bZWMPL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/51Iz1PetkvL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/71fl+GE4x1L._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/710RhxL9RpL._SY500_.jpg",
        description: "Trendy Urban Design: The STEMINAR Sneaker features a sleek and contemporary design, combining minimalistic elements with eye-catching accents. The upper is constructed from a high-quality TPR (Rubber) material, allowing for optimal airflow and ventilation",
        rating: 4.0,
        discount: 69,
        category: "men"
      },
      {
        id: 9,
        name: "YOHO Radiance Women’s Stylish Comfortable Premium Casual Sneakers",
        originalPrice:2899,
        discountPrice: 1681,
        image_1: "https://m.media-amazon.com/images/I/51dCSOCu4bL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/51v9oanluWL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/61NthB5KUjL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61jf8yXFbPL._SY500_.jpg",
        description: "Introducing Yoho Radiance sneakers - where comfort meets street style. The flower lining on these women sneakers adds detailing to the design Offering trendy looks and comfortable insoles, these sneakers are perfect for outdoors",
        rating: 3.2,
        discount: 42,
        category: "women"
      },
      {
        id: 10,
        name: "Bella Toes White Women Casual Shoes",
        originalPrice:999,
        discountPrice: 794,
        image_1: "https://m.media-amazon.com/images/I/51mvBkKQn2L._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61uKJ9QgmnL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/61UBAzBoa2L._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61V6vd72bOL._SY500_.jpg",
        description: "Rendered with the modern-day appeal, this marvellous pair for casual sneakers for women is simply perfect for casual occasion. It has been crafted to provide you with ultimate looks, unbeatable style and cozy comfort. ",
        rating: 3.7,
        discount: 21,
        category: "women"
      },
      {
        id: 11,
        name: "ella Toes Women|Girls White Casual Stylish Sneaker Shoes for Women's| Girls",
        originalPrice:250,
        discountPrice: 737,
        image_1: "https://m.media-amazon.com/images/I/61RSgBTnDyL._SY500_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61JQWUVXO2L._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/61FuPpuFb4L._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61mHgPuvf2L._SY500_.jpg",
        description: "Bella Toes Women New Casual shoes. Very lightweigt new TPR sole. Smart and trendy Casual shoes for girls and women. Pair it with jeans, shorts,skirts for smart casual look.",
        rating: 3.6,
        discount: 43,
        category: "women"
      },
      {
        id: 12,
        name: "Kraasa Casual Sneakers for Women | Latest Trend Casual Shoes, Walking Shoes for Women",
        originalPrice:999,
        discountPrice: 499,
        image_1: "https://m.media-amazon.com/images/I/71YGQlB80qL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/81QRVTk8CfL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/71q2OZO50iL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/71xfta3InRL._SY500_.jpg",
        description: "LIGHTWEIGHT AND BREATHABLE: Sweat-absorbing Upper, Stretchy Air Mix Rubber Outsole Offer Lightweight, Breathability And Shock Absorption, Bringing You A Dry And Cool Life.",
        rating: 3.6,
        discount: 50,
        category: "women"
      },
      {
        id: 13,
        name: "YOHO Chonks Women’s Sporty Comfortable Chunky Sneakers",
        originalPrice:2999,
        discountPrice: 1799,
        image_1: "https://m.media-amazon.com/images/I/61FPXtyqdoL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61sGMKxlvLL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/716cddPMuEL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/81xG7KKwNjL._SY500_.jpg",
        description: "Meet Yoho's Chonks Women Sneakers. These babies are light on your feet and give a trendy look. They come with an anti-skid sole, perfect for walking around with confidence. The cushion insole makes them super comfy to wear.",
        rating: 3.1,
        discount: 40,
        category: "women"
      },
      {
        id: 14,
        name: "ASIAN Casual Sneaker Shoes for Women | Soft Cushioned Insole",
        originalPrice:999,
        discountPrice: 600,
        image_1: "https://m.media-amazon.com/images/I/71v6STXRsgL._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/71cCn8QS4AL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/71kCrCJ8uvL._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/71q9ei1VstL._SY500_.jpg",
        description: "Sole Features: Height increasing non marking pvc outsole made with light weight compound and orthopedic memory foam shoes which provides extra comfort to your feet with a perfect grip.",
        rating: 3.6,
        discount: 40,
        category: "women"
      },
      {
        id: 15,
        name: "Vendoz Rechargable LED Lights Party Dance Shoes with USB Charging for Women Girls and Children",
        originalPrice:3999,
        discountPrice: 1999,
        image_1: "https://m.media-amazon.com/images/I/51HGFy+0mPL._SY500_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61UapANoxyL._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/71K9ulrx1FL._SY625_.jpg",
        image_4: "https://m.media-amazon.com/images/I/51JhSxZG+sL._SY500_.jpg",
        description: " To charge the shoe, gently pull the mini USB charging slot hidden inside the back collar of the shoe. 2. Press the button on the mini USB slot to switch on or for changing the light modes.",
        rating: 3.8,
        discount: 50,
        category: "women"
      },
      {
        id: 16,
        name: "AMIFAA Women/Girls Casual Shoes",
        originalPrice:250,
        discountPrice: 599,
        image_1: "https://m.media-amazon.com/images/I/610ILkK-gtS._SY625_.jpg",
        image_2: "https://m.media-amazon.com/images/I/61lDXF61-LS._SY500_.jpg",
        image_3: "https://m.media-amazon.com/images/I/61X5hRXvjfS._SY500_.jpg",
        image_4: "https://m.media-amazon.com/images/I/61+8-c1XnjS._SY500_.jpg",
        description: "We minimize the weight of shoes and ensure that you do not add to your burden while protecting your feet..",
        rating: 3.6,
        discount: 76,
        category: "women" 
      }
      
      
]

export default Data;